export { default as Home } from './Home';
export { default as Login } from './Login';
export { default as Register } from './Register';
export { default as Account } from './Account';
export { default as NavBar } from './NavBar';
export { default as Loader } from './Loader';
export { default as Dashboard } from './Dashboard';
export { default as UnAuthorised } from './UnAuthorised';
export { default as AddTeamForm } from './AddTeamForm';